spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: resources/static/Temp
      max-file-size: 4MB
      max-request-size: 55MB

  resources:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/placehub__dev?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  security:
    csrf:
      enabled: true
    oauth2:
      client:
        registration:
          kakao:
            scope: account_email, profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost/login/oauth2/code/kakao
            client-authentication-method: POST
          naver:
            scope:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost/login/oauth2/code/naver
          google:
            redirect-uri: https://localhost/login/oauth2/code/google
            client-name: Google
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

custom:
  api:
    coord:
      start-x: 126.84
      start-y: 37.44
      end-x: 127.16
      end-y: 37.72

    category-code:
      culture: CT1
      tour: AT4
      restaurant: FD6
      cafe: CE7