spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lldjlocal
    password: 1234
    url: jdbc:mysql://172.17.0.1:3306/placehub__prod?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

custom:
  site:
    baseUrl: https://www.placehub.xyz
