server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: 123456
    key-store: keystore.p12
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
custom:
  site:
    baseUrl: https://localhost